= 前置工作之安装JDK和元数据库

**目录**

. <<JDK>> +
. 元数据库 +
.. <<安装postgresql客户端>> +
.. <<安装和配置PostrgeSQL Server>>

== JDK

在所有节点上安装openjdk1.8
....
yum -y install openjdk8-8.0+232_9-cloudera
....

== 元数据库

推荐安装PostgreSQL 10，将PostgreSQL Server安装在主节点1上。 +
**注意：** RHEL或CentOS发行版默认自带的是PostgreSQL 9.2，需要更新为10版本。

=== 安装postgresql客户端

**在所有的主机上执行:**
....
yum -y install postgresql-jdbc*
cp /usr/share/java/postgresql-jdbc.jar /usr/share/java/postgresql-connector-java.jar
chmod 644 /usr/share/java/postgresql-connector-java.jar

yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
yum -y install https://yum.postgresql.org/10/redhat/rhel-7-x86_64/python3-psycopg2-2.8.5-1.rhel7.x86_64.rpm 
yum -y install postgresql10
....

=== 安装和配置PostrgeSQL Server

**在主节点1上执行:**

Step1.  安装PostrgeSQL
....
yum -y install postgresql10-server
/usr/pgsql-10/bin/postgresql-10-setup initdb
systemctl enable postgresql-10
systemctl start postgresql-10
....

Step2.  安装psycopg2 lib:
....
yum -y install pip
pip install psycopg2==2.7.5 --ignore-installed
....

Step3.  修改密码，初始化密码为Admin1234 + 
**注意：** 该步为交互式，无法远程执行
....
sudo -u postgres psql
\password
....

Step4.  修改配置 +
**注意：** 该步为交互式，无法远程执行 +
vi /var/lib/pgsql/10/data/pg_hba.conf
....
# IPv4 local connections:
host    all             all             127.0.0.1/32           ident
修改为：
host    all             all             127.0.0.1/32           password
....

Step5.  修改配置
....
echo "listen_addresses = '*'
max_connections = 1000" >> /var/lib/pgsql/10/data/postgresql.conf
echo "
local   all             posgtres                                trust
host    all             all             0.0.0.0/0               md5
local   all             all                                     md5
" >> /var/lib/pgsql/10/data/pg_hba.conf
....

Step6.  创建数据库和用户
....
sudo -u postgres psql << EOF
    CREATE ROLE scm LOGIN PASSWORD 'admin';
    CREATE DATABASE scm OWNER scm ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE amon LOGIN PASSWORD 'admin';
    CREATE DATABASE amon OWNER amon ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE rman LOGIN PASSWORD 'admin';
    CREATE DATABASE rman OWNER rman ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE hue LOGIN PASSWORD 'admin';
    CREATE DATABASE hue OWNER hue ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE hive LOGIN PASSWORD 'admin';
    CREATE DATABASE metastore OWNER hive ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE oozie LOGIN PASSWORD 'admin';
    CREATE DATABASE oozie OWNER oozie ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE das LOGIN PASSWORD 'admin';
    CREATE DATABASE das OWNER das ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE smm LOGIN PASSWORD 'admin';
    CREATE DATABASE smm OWNER smm ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE rangeradmin LOGIN PASSWORD 'admin';
    CREATE DATABASE ranger OWNER rangeradmin ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE smm LOGIN PASSWORD 'admin';
    CREATE DATABASE smm OWNER smm ENCODING 'UTF8' TEMPLATE template0;
    CREATE ROLE das LOGIN PASSWORD 'admin';
    CREATE DATABASE das OWNER das ENCODING 'UTF8' TEMPLATE template0;
EOF
....

Step7.  重启数据库  
systemctl restart postgresql-10

